server:
  port: 8080

spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      data-locations: classpath:/data.sql
      schema-locations: classpath:/sheme.sql

  datasource:
    username: dbadmin
    password: 123

  h2:
    console:
      enabled: true