version: '2'

services:

  app:
    container_name: stock-management
    image: 'stock-management:latest'
    build: .
    ports:
      - "8080:8080"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"